export const COMPANY_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING',
  DISABLED: 'DISABLED',
}

export const COMPANY_STATUSES_PRETTY = {
  [COMPANY_STATUSES.ACTIVE]: 'Active',
  [COMPANY_STATUSES.DISABLED]: 'Disabled',
  [COMPANY_STATUSES.INACTIVE]: 'Inactive',
  [COMPANY_STATUSES.PENDING]: 'Pending',
}

export const COMPANY_STATUSES_SELECT_VALUES = [
  { value: COMPANY_STATUSES.ACTIVE, label: COMPANY_STATUSES_PRETTY[COMPANY_STATUSES.ACTIVE] },
  { value: COMPANY_STATUSES.DISABLED, label: COMPANY_STATUSES_PRETTY[COMPANY_STATUSES.DISABLED] },
  { value: COMPANY_STATUSES.INACTIVE, label: COMPANY_STATUSES_PRETTY[COMPANY_STATUSES.INACTIVE] },
  { value: COMPANY_STATUSES.PENDING, label: COMPANY_STATUSES_PRETTY[COMPANY_STATUSES.PENDING] },
]

export const COMPANY_STATUSES_VALUES = [
  COMPANY_STATUSES.ACTIVE,
  COMPANY_STATUSES.DISABLED,
  COMPANY_STATUSES.INACTIVE,
  COMPANY_STATUSES.PENDING,
]
