export const FILE_STATUSES = {
  INITIALIZED: 'Initialized',
  UPLOADED: 'Uploaded',
  IN_PROGRESS: 'In progress',
  PROCESSED: 'Processed',
  PARTIALLY_PROCESSED: 'Partially Processed',
}

export const FILE_UPLOAD_FROM = {
  GMAIL: 'GMAIL',
  SES: 'SES',
  MANUALLY: 'MANUALLY',
  SAMPLE: 'SAMPLE',
  SAMPLE_FORM: 'SAMPLE_FORM',
  SAMPLE_MEDICARE: 'SAMPLE_MEDICARE',
  SAMPLE_PDF: 'SAMPLE_PDF',
  SAMPLE_RENTAL_APP: 'SAMPLE_RENTAL_APP',
  SAMPLE_TABLE: 'SAMPLE_TABLE',
  SAMPLE_TEXT: 'SAMPLE_TEXT',
}
