export const NODE_TYPES = {
  UPLOAD_DOCUMENT: 'uploadDocument',
  FORM_EXTRACTION: 'formExtraction',
  TEXT_EXTRACTION: 'textExtraction',
  TABLE_EXTRACTION: 'tableExtraction',
  QUESTION_ANSWERING: 'questionAnswering',
  QUESTION_ANSWERING_CHOICE: 'questionAnsweringChoice',
  IDENTITY_VALIDATION: 'identityValidation',
  OUTPUT_CSV: 'outputCsv',
  OUTPUT_JSON: 'outputJson',
  GMAIL_READER: 'gmailReader',
  EMAIL_TRIGGER: 'emailTrigger',
}

export type NODE_TYPE = (typeof NODE_TYPES)[keyof typeof NODE_TYPES]

export const TEMPLATES = {
  IDENTITY_VALIDATION_TEMPLATE: 'identityValidationTemplate',
  RENTAL_APP_TEMPLATE: 'rentalAppTemplate',
  TEXT_EXTRACTION_TEMPLATE: 'textExtractionTemplate',
  FORM_EXTRACTION_TEMPLATE: 'formExtractionTemplate',
  TABLE_EXTRACTION_TEMPLATE: 'tableExtractionTemplate',
}

export type TEMPLATE_TYPE = (typeof TEMPLATES)[keyof typeof TEMPLATES]

export const INPUT_NODE_TYPES = [NODE_TYPES.UPLOAD_DOCUMENT, NODE_TYPES.GMAIL_READER, NODE_TYPES.EMAIL_TRIGGER]
export const OUTPUT_NODE_TYPES = [NODE_TYPES.OUTPUT_CSV, NODE_TYPES.OUTPUT_JSON]
export const PROCESSING_NODE_TYPES = [
  NODE_TYPES.FORM_EXTRACTION,
  NODE_TYPES.TEXT_EXTRACTION,
  NODE_TYPES.TABLE_EXTRACTION,
  NODE_TYPES.QUESTION_ANSWERING,
  NODE_TYPES.QUESTION_ANSWERING_CHOICE,
]

export const TASK_TYPES = {
  TASK: 'TASK',
  PARALLEL: 'PARALLEL',
  CHOICE: 'CHOICE',
  MAP: 'MAP',
}

export const TASK_SERVICES = {
  START: 'START',
  FINISH: 'FINISH',
  EXTRACT_FORM: 'EXTRACT_FORM',
  EXTRACT_TABLE: 'EXTRACT_TABLE',
  EXTRACT_TEXT: 'EXTRACT_TEXT',
  SAVE_EMBEDDING: 'SAVE_EMBEDDING',
  DETERMINE_DOCUMENTS_RAG: 'DETERMINE_DOCUMENTS_RAG',
  QA: 'QA',
  QA_CHOICE: 'QA_CHOICE',
}

export const TASK_CONDITIONS_TYPES = {
  INITIALIZED: 'INITIALIZED',
  PROCESSING: 'PROCESSING',
  SUCCEED: 'SUCCEED',
  FAILED: 'FAILED',
}
