export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  TENANT_USER: 'TENANT_USER',
  USER: 'USER',
}

export const ADMIN_ROLES = [USER_ROLES.SUPER_ADMIN, USER_ROLES.SYSTEM_ADMIN, USER_ROLES.TENANT_ADMIN]

export const USER_ROLES_ARRAY = Object.values(USER_ROLES)

export type TYPE_USER_ROLES = (typeof USER_ROLES)[keyof typeof USER_ROLES]

export const USER_ROLES_PRETTY_NAMES = {
  [USER_ROLES.SUPER_ADMIN]: 'Super Admin',
  [USER_ROLES.SYSTEM_ADMIN]: 'System Admin',
  [USER_ROLES.TENANT_ADMIN]: 'Tenant Admin',
  [USER_ROLES.USER]: 'User',
}
