export const PROCESSING_INITIAL_STATE = {
  customNodes: {},
  putCustomNode: () => {},
  getCustomNode: () => undefined,
  getParentInputNode: () => null,
  removeCustomNode: () => undefined,
  setRootNodeId: () => {},
  onConnect: () => {},
  edges: [],
  onEdgesChange: () => {},
  handleEdgesDelete: () => {},
  handleNodesDelete: () => {},
  nodes: [],
  onNodesChange: () => {},
  onDrop: () => {},
  runProcessingFlow: () => {},
  setProcessingResults: () => {},
  isRunning: false,
  setIsRunning: () => {},
  setCurrentProcessingResult: () => {},
  setError: () => {},
  resetProcessingFlow: () => {},
  selectedEmailAttachments: [],
  setSelectedEmailAttachments: () => {},
  getRootNode: () => undefined,
  isFilesPreprocessing: false,
  setIsFilesPreprocessing: () => {},
  setPredefinedTemplateType: () => {},
  serializeState: () => '',
  deserializeState: () => {},
  setEmailTriggerResults: () => {},
  setEnableSampleDocuments: () => false,
}
